---
virtualbox:
  hosts:
#     centos_virt:
#     ubuntu_virt:
#     ubuntu_virt_home:
     ubuntu_virt_sa:

all_hosts:
  children:
    ec_htp:
      vars:
        full_name: "Educational Center of HTP"
      hosts:
        centos_virt:
          ansible_user: vagrant
          ansible_host: 10.13.210.56
        ubuntu_virt:
          ansible_user: vagrant
          ansible_host: 10.13.210.59
        ubuntu_virt_home:
          ansible_user: vagrant
          ansible_host: 192.168.0.103
        ubuntu_virt_sa:
          ansible_user: user
          ansible_host: 192.168.254.224