---
virtualbox:
  hosts:
#     centos_virt:
     ubuntu_virt:

all_hosts:
  children:
    ec_htp:
      vars:
        full_name: "Educational Center of HTP"
      hosts:
        centos_virt:
          ansible_user: vagrant
          ansible_host: 10.13.210.56
        ubuntu_virt:
          ansible_user: user  
          ansible_host: 10.13.210.53
