---

- name: Include deploy for Debian system
  include: docker_debian.yaml
  when: ansible_os_family == 'Debian'

- name: Include deploy for RedHat system
  include: docker_redhat.yaml
  when: ansible_os_family == 'RedHat'
